create table if not exists public.login_attempt_audit (
  id bigint generated by default as identity primary key,
  event_type text not null default 'login_failure',
  reason text,
  fail_count integer not null default 0,
  lock_until timestamptz,
  client_reported_at timestamptz,
  client_origin text,
  client_host text,
  page_path text,
  page_href text,
  masked_ip text,
  ip_address text,
  user_agent text,
  request_headers jsonb not null default '{}'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists login_attempt_audit_created_at_idx
  on public.login_attempt_audit (created_at desc);

create index if not exists login_attempt_audit_ip_address_idx
  on public.login_attempt_audit (ip_address);

create index if not exists login_attempt_audit_event_type_idx
  on public.login_attempt_audit (event_type);

alter table public.login_attempt_audit enable row level security;

revoke all on public.login_attempt_audit from anon;
revoke all on public.login_attempt_audit from authenticated;

comment on table public.login_attempt_audit is
  'Backend audit records for failed login attempts captured by the homepage.';
